name: fuzzingbook
channels:
  - defaults
  - anaconda-fusion
  - conda-forge
dependencies:
  - matplotlib
  - numpy
  - pandas
  - graphviz
  - pip:
      - graphviz
      - jupyter_contrib_nbextensions
