name: fuzzingbook
channels:
  - defaults
  - anaconda-fusion
  - conda-forge
  - bjornfjohansson
  - anaconda-platform
  - ameurer
dependencies:
  - matplotlib
  - numpy
  - scipy
  - pandas
  - graphviz
  - autopep8
  - notedown
  - mypy
  - selenium
  - geckodriver
  - z3
  - pip:
      - graphviz
      - svglib
      - jupyter_contrib_nbextensions
      - astor
      - astunparse
